import { type IndexerConfig } from './types'

export const default_config: Record<'indexer', IndexerConfig> = {
  indexer: {
    enabled: true,
    ignore_patterns: [
      '.git/',
      '.agentic/',
      '.vscode',
      '.idea',
      '*.md',
      'migrations',
      'drizzle_migrations',
      'node_modules',
      '*.lock',
      '.prettier*',
      '.claude/*.json',
      '__pycache__',
      'venv',
      'poetry',
      'docker',
      'doc/',
      '**/tests/fixtures/**',
      '**/__tests__/fixtures/**',
      '**/testdata/**',
      '**/tests/mocks/**',
      '**/tests/mock/**',
      '**/tests/stubs/**',
    ],
    extnToLangMap: {
      tsx: 'tsx',
      ts: 'typescript',
      js: 'javascript',
      jsx: 'javascript',
      json: 'json',
      py: 'python',
    },
    testFilePatterns: ['*.{test,spec}.*', '__tests__/**', 'tests/**'],
    entryPointPatterns: ['index.*', 'main.*', 'app.*'],
    languages: {
      typescript: {
        extensions: ['.ts', '.mts', '.cts'],
        lsp_command: ['typescript-language-server', '--stdio'],
        lang_features_paths: [
          'node_modules/typescript/lib',
          'node_modules/@types/node',
          'node_modules/%40types/node',
          'node_modules/@types/bun',
          'node_modules/%40types/bun',
        ],
        treesitter: {
          language_name: 'typescript',
          signature_max_length: 400,
        },
        tsconfig_paths: [
          '/tsconfig.json',
          '/tsconfig.*.json',
          '!/tsconfig.build.json',
          '!/tsconfig.test.json',
          'apps/*/tsconfig.json',
          'apps/*/tsconfig.*.json',
          'packages/*/tsconfig.json',
          'packages/*/tsconfig.*.json',
        ],
        import_resolution: {
          asset_extensions: [
            '.css',
            '.scss',
            '.sass',
            '.less',
            '.svg',
            '.png',
            '.jpg',
            '.jpeg',
            '.webp',
            '.json',
            '.yaml',
            '.yml',
            '.toml',
          ],
        },
      },
      tsx: {
        extensions: ['.tsx'],
        lsp_command: ['typescript-language-server', '--stdio'],
        lang_features_paths: [
          'node_modules/typescript/lib',
          'node_modules/@types/node',
          'node_modules/%40types/node',
          'node_modules/@types/bun',
          'node_modules/%40types/bun',
        ],
        treesitter: {
          language_name: 'tsx',
          signature_max_length: 400,
        },
        tsconfig_paths: [
          '/tsconfig.json',
          '/tsconfig.*.json',
          '!/tsconfig.build.json',
          '!/tsconfig.test.json',
          'apps/*/tsconfig.json',
          'apps/*/tsconfig.*.json',
          'packages/*/tsconfig.json',
          'packages/*/tsconfig.*.json',
        ],
        import_resolution: {
          asset_extensions: [
            '.css',
            '.scss',
            '.sass',
            '.less',
            '.svg',
            '.png',
            '.jpg',
            '.jpeg',
            '.webp',
            '.json',
            '.yaml',
            '.yml',
            '.toml',
          ],
        },
      },
      python: {
        extensions: ['.py'],
        lsp_command: ['basedpyright-langserver', '--stdio'],
        lang_features_paths: ['/usr/lib/python', 'typeshed', 'django'],
        treesitter: {
          language_name: 'python',
          signature_max_length: 400,
        },
        import_resolution: {
          asset_extensions: [
            '.css',
            '.scss',
            '.sass',
            '.less',
            '.svg',
            '.png',
            '.jpg',
            '.jpeg',
            '.webp',
            '.json',
            '.yaml',
            '.yml',
            '.toml',
          ],
        },
      },
      javascript: {
        extensions: ['.js', '.mjs', '.cjs'],
        lsp_command: ['typescript-language-server', '--stdio'],
        lang_features_paths: [
          'node_modules/typescript/lib',
          'node_modules/@types/node',
          'node_modules/%40types/node',
          'node_modules/@types/bun',
          'node_modules/%40types/bun',
        ],
        treesitter: {
          language_name: 'javascript',
          signature_max_length: 400,
        },
        import_resolution: {
          asset_extensions: [
            '.css',
            '.scss',
            '.sass',
            '.less',
            '.svg',
            '.png',
            '.jpg',
            '.jpeg',
            '.webp',
            '.json',
            '.yaml',
            '.yml',
            '.toml',
          ],
        },
      },
    },
    docstring_generation: {
      enabled: false,
      provider: 'ollama',
      write_to_file: false,
      exclude_generation_patterns: [
        '**/tests/fixtures/**',
        '**/__tests__/fixtures/**',
        '**/testdata/**',
        '**/tests/mocks/**',
        '**/tests/mock/**',
        '**/tests/stubs/**',
      ],
      claude: {
        api_key: process.env.CLAUDE_API_KEY || '',
        model: 'claude-haiku-4-5',
      },
      gemini: {
        api_key: process.env.GEMINI_API_KEY || '',
        model: 'gemini-3-flash-preview',
      },
      openai: {
        api_key: process.env.OPENAI_API_KEY || '',
        model: 'gpt-4o-mini',
      },
      ollama: {
        base_url: 'http://localhost:11434',
        model: 'deepcoder',
      },
    },
    agent_config_candidates: [
      '.cursorrules',
      'CLAUDE.md',
      'AGENTS.md',
      'AGENT.md',
      'copilot-instructions.md',
      '.github/copilot-instructions.md',
      '.clinerules',
      '.windsurfrules',
    ],
    embedder: {
      enabled: false,
      provider: 'ollama',
      ollama: {
        base_url: 'http://localhost:11434',
        model: 'nomic-embed-text',
      },
    },
  },
}
